# Generated by Django 6.0.5 on 2026-07-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='user',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
