# Generated by Django 6.0.5 on 2026-06-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productvariant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('ّFree Size', 'ّFree Size'), ('ّ38-44', 'ّ38-44'), ('ّ-', 'ّ-')], max_length=10),
        ),
    ]
